# Generated by Django 3.1 on 2020-10-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
    ]
