# Generated by Django 3.1 on 2020-10-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201013_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='network.user'),
            preserve_default=False,
        ),
    ]
