# Generated by Django 3.1 on 2020-10-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_liked_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liked_by', 'post')},
        ),
    ]
